apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress-live.yaml
  - ingress-redirect.yaml
  - ingress-preview.yaml
  - certificate.yaml
